//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Booking_System_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING
    {
        public int BKID { get; set; }
        public string SUBJECT { get; set; }
        public string MEETING_WITH { get; set; }
        public System.DateTime BOOKING_DATE { get; set; }
        public System.TimeSpan BOOKING_TIME { get; set; }
        public int CLIENT_ID { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
    }
}
